name: tflearn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
      - ipykernel
      - jupyter
      - matplotlib
      - dvc
      - tensorflow
      - tensorflow_probability
      - keras
      - matplotlib
      - numpy
      - scipy
      

